# Generated by Django 3.2.4 on 2022-04-01 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Object',
            fields=[
                ('idObject', models.IntegerField(primary_key=True, serialize=False)),
                ('nameObject', models.CharField(max_length=80)),
                ('descriptionObject', models.CharField(max_length=250)),
                ('xObject', models.FloatField()),
                ('yObject', models.FloatField()),
            ],
        ),
    ]
