# Generated by Django 3.2.4 on 2022-04-01 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objectsApi', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Object',
            new_name='Objects',
        ),
    ]
