# Generated by Django 3.2.4 on 2022-04-01 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objectsApi', '0002_rename_object_objects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objects',
            name='idObject',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
