# Generated by Django 3.2.4 on 2022-04-01 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objectsApi', '0003_alter_objects_idobject'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='objects',
            options={'verbose_name': 'Объект', 'verbose_name_plural': 'Объекты'},
        ),
        migrations.AlterField(
            model_name='objects',
            name='descriptionObject',
            field=models.CharField(max_length=250, verbose_name='Описание объекта'),
        ),
        migrations.AlterField(
            model_name='objects',
            name='idObject',
            field=models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='ID объекта'),
        ),
        migrations.AlterField(
            model_name='objects',
            name='nameObject',
            field=models.CharField(max_length=80, verbose_name='Наименование объекта'),
        ),
        migrations.AlterField(
            model_name='objects',
            name='xObject',
            field=models.FloatField(verbose_name='Координата X на карте'),
        ),
        migrations.AlterField(
            model_name='objects',
            name='yObject',
            field=models.FloatField(verbose_name='Координата Y на карте'),
        ),
    ]
